name: Pull Request Size

on:
  # Triggers the workflow on pull request context
  pull_request_target:
    types: [ opened, edited, reopened, synchronize ]
    paths-ignore:
    - 'vendor/**'

  # Triggers the workflow on issue or pull request comment
  #pull_request_review_comment:
  issue_comment:

jobs:
  pr-size:
    name: PrSizeLabeler
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '30'
          s_label: 'size/S'
          s_max_size: '100'
          m_label: 'size/M'
          m_max_size: '300'
          l_label: 'size/L'
          l_max_size: '1000'
          xl_label: 'size/XL'
          fail_if_xl: 'false'
