name: Merge on LGTM Label
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  merge-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: chnsz/prow-github-actions@v1.0.0
        if: ${{ secrets.ROBOT_PAT }}
        with:
          jobs: 'lgtm'
          github-token: "${{ secrets.ROBOT_PAT }}"
          # this configuration is optional and will default to 'merge'
          # possible options are 'merge', 'rebase', or 'squash'
          merge-method: 'squash'
